version: "3.8"
services:
  spring-boot:
    image: maven:3.6.3-jdk-11
    container_name: spring-boot
    volumes:
      - ./spring-boot:/app
    working_dir: /app
    ports:
      - 3000:8080
      - 35729:35729
    command: mvn spring-boot:run

    depends_on:
      - dbpostgresql

  dbpostgresql:
    container_name: dbpostgresql
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432