FROM maven:3.6.3-jdk-11 as dev

WORKDIR /work

COPY . /work/
RUN ls
RUN mvn install

RUN chmod +x /work/target/spring-boot-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/work/target/spring-boot-0.0.1-SNAPSHOT.jar"]